var mix = require("laravel-mix");
const glob = require("glob");
const path = require("path");
// const forEach = require("lodash/forEach");
const trim = require("lodash/trim");
var fs = require("fs");

let systemVar = JSON.parse(fs.readFileSync("app/MainApp/config/_system.json"));
var publicPath = path.normalize(systemVar.public_path?trim(systemVar.public_path,'/'):'public');

/*
 |--------------------------------------------------------------------------
 | Mix config
 |--------------------------------------------------------------------------
 */

mix.options({
    postCss: [require("autoprefixer")]
});
mix.setPublicPath(publicPath);

/*
 |--------------------------------------------------------------------------
 | Webpack config
 |--------------------------------------------------------------------------
 */

mix.webpackConfig({
    module: {
        rules: [
            {
                test: /node_modules(?:\/|\\).+\.js$/,
                loader: "babel-loader",
                include: [
                    path.join(__dirname, "node_modules/vue-echarts"),
                    path.join(__dirname, "node_modules/resize-detector"),
                    path.join(__dirname, "node_modules/vue-masonry")
                ]
            }
        ]
    },
    resolve: {
        alias: {
            "@": path.join(__dirname, "resources/assets/src"),
            node_modules: path.join(__dirname, "node_modules")
        }
    },
    output: {
        chunkFilename: "dist/chunks/[name].[contenthash].js"
    }
});

/*
 |--------------------------------------------------------------------------
 | Vendor assets
 |--------------------------------------------------------------------------
 */

let assetPath = "resources/assets/";

function mixAssetsDir(query, cb) {
    (glob.sync(query) || []).forEach(f => {
        f = f.replace(/[\\\/]+/g, "/");
        cb(f, path.normalize(f.replace("resources/assets", publicPath + "/dist")));
    });
}

const sassOptions = {
    // precision: 5,
    implementation: () => require("node-sass")
};

// Core javascripts
if(systemVar.web_admin.web || systemVar.web_admin.full_vue)
    mixAssetsDir(assetPath+"vendor/js/**/*.js", (src, dest) => mix.scripts(src, dest));//web & full vue
if(systemVar.web_admin.web)
    mixAssetsDir(assetPath+"vendor/webjs/**/*.js", (src, dest) => mix.scripts(src, dest));//web

// Web Libs
if(systemVar.web_admin.web){
    mixAssetsDir(assetPath+
        'vendor/weblibs/**/*.js', 
        (src, dest) => mix.scripts(src, dest)
    );//web
    mixAssetsDir(assetPath+
        'vendor/weblibs/**/!(_)*.scss', 
        (src, dest) => mix.sass(src, dest.replace(/\.scss$/, '.css'), sassOptions)
    );//web

}

// Fonts
if(systemVar.web_admin.web || systemVar.web_admin.full_vue) {
    mixAssetsDir(assetPath+"vendor/fonts/*.css", (src, dest) => mix.copy(src, dest));
    mixAssetsDir(assetPath+"vendor/fonts/*/*", (src, dest) => mix.copy(src, dest));
}

/*
----------------------------------------------------------------------
generate config package.json
----------------------------------------------------------------------
*/
// var varPackage = JSON.parse(fs.readFileSync("app/MainApp/config/package.json"));
// var packageLocal = JSON.parse(fs.readFileSync("app/MainApp/config/_packageLocal.json"));

// TIDAK JADI, SEMENTARA DISATUIN DI appconfig.php
// (glob.sync("vendor/hp-synapse/*/packageconfig.json") || []).forEach(f => {
//     f = f.replace(/[\\\/]+/g, "/");
//     tmpfile = JSON.parse(fs.readFileSync(f));
//     varPackage[tmpfile.package_namespace] = tmpfile;
// });
// (glob.sync("app/MainApp/Modules/*/packageconfig.json") || []).forEach(f => {
//     f = f.replace(/[\\\/]+/g, "/");
//     tmpfile = JSON.parse(fs.readFileSync(f));
//     varPackage[tmpfile.package_namespace] = tmpfile;
// });
// fs.writeFileSync(
//     "app/MainApp/config/package.json",
//     JSON.stringify(varPackage, null, 4)
// );

/*
----------------------------------------------------------------------
generate loader store, router, routerAdmin dan init.js untuk package
----------------------------------------------------------------------
*/
// var filePath = "";//path real saat build
// var packagePath = "";//path untuk load selain main.js
// var packageMainPath = "";//path untuk load main.js

// var moduleMainJs = [
//     "// DO NOT EDIT MANUALY UNLESS YOU KNOW WHAT YOU ARE DOING \n" +
//     "// This files is autogenerated on build and by app-generator \n" +
//     "// containt list all main.js for every module registered to this project \n\n"
// ];
// var moduleStore = [
//     "// DO NOT EDIT MANUALY UNLESS YOU KNOW WHAT YOU ARE DOING \n" +
//     "// This files is autogenerated on build and by app-generator \n" +
//     "// load all vuex state for every module registered to this project \n\n"
// ];
// var moduleStoreNamespace = [];
// var moduleRouter = [
//     "// DO NOT EDIT MANUALY UNLESS YOU KNOW WHAT YOU ARE DOING \n" +
//     "// This files is autogenerated on build and by app-generator \n" +
//     "// load all router for every module registered to this project \n\n"
// ];
// var moduleRouterNamespace = [];
// var moduleRouterAdmin = [
//     "// DO NOT EDIT MANUALY UNLESS YOU KNOW WHAT YOU ARE DOING \n" +
//     "// This files is autogenerated on build and by app-generator \n" +
//     "// load all router admin endpoint for every module registered to this project \n\n"
// ];
// var moduleRouterAdminNamespace = [];
// var curpath = __dirname.replace(/[\\\/]+/g,"/");
// forEach(varPackage,(value,key)=>{
//     if(value.is_package){
//         filePath = "vendor/hp-synapse/" + value.package_dir + "/src/"
//         packagePath = curpath + "/vendor/hp-synapse/" + value.package_dir + "/src/";
//         packageMainPath = curpath + "/vendor/hp-synapse/" + value.package_dir + "/src/";
//     }else{
//         filePath = "app/MainApp/Modules/" + value.package_dir + "/"
//         packagePath = "../../../Modules/" + value.package_dir + "/";
//         packageMainPath = "../../Modules/" + value.package_dir + "/";
//     }

//     //load package hanya jika aktif saja
//     if(packageLocal[value.package_namespace]['enable']){
//         //untuk loader main.js
//         if (fs.existsSync(filePath + "resources/js/main.js")) {
//             moduleMainJs.push('require("' + packageMainPath + 'resources/js/main");' + "\n");
//         }
        
//         //untuk loader vuex store
//         if (fs.existsSync(filePath + "resources/js/store/store.js")) {
//             moduleStore.push("import " + value.package_namespace + ' from "' + packagePath + 'resources/js/store/store";' + "\n");
//             moduleStoreNamespace.push("    ..." + value.package_namespace);
//         }

//         //untuk loader vue router
//         if (fs.existsSync(filePath + "resources/js/router/index.js")) {
//             moduleRouter.push("import " + value.package_namespace + ' from "' + packagePath + 'resources/js/router/index";' + "\n");
//             moduleRouterNamespace.push("    .concat(" + value.package_namespace + ")");
//         }

//         //untuk loader vue router admin endpoint
//         if (fs.existsSync(filePath + "resources/js/router/indexAdmin.js")) {
//             moduleRouterAdmin.push("import " + value.package_namespace + ' from "' + packagePath + 'resources/js/router/indexAdmin";' + "\n");
//             moduleRouterAdminNamespace.push("    .concat(" + value.package_namespace + ")");
//         }
//     }
    
// });

// //write loader main.js
// fs.writeFileSync(
//     "app/MainApp/resources/js/modules.js",
//     moduleMainJs.join('')
// );

// //write loader vuex store
// fs.writeFileSync(
//     "app/MainApp/resources/js/store/modules.js",
//     moduleStore.join('') + 
//     "\nconst store = {\n" +
//     moduleStoreNamespace.join(",\n") + "\n" +
//     "};\n\nexport default store;"
// );

// //write loader router
// fs.writeFileSync(
//     "app/MainApp/resources/js/router/modules.js",
//     moduleRouter.join('') + 
//     "\nconst routes = []\n" +
//     moduleRouterNamespace.join("\n") + ";\n\n" +
//     "export default routes;"
// );

// //write loader router admin
// fs.writeFileSync(
//     "app/MainApp/resources/js/router/modulesAdmin.js",
//     moduleRouterAdmin.join('') + 
//     "\nconst routes = []\n" +
//     moduleRouterAdminNamespace.join("\n") + ";\n\n" +
//     "export default routes;"
// );

/*
 |--------------------------------------------------------------------------
 | Entry point
 |--------------------------------------------------------------------------
 */

if(systemVar.web_admin.full_vue){
    var buildJs = require("./app/MainApp/resources/js/build.js");
    buildJs(fs,mix);

    mix.js("resources/assets/src/entry-point.js", "dist/app.js").version();//full vue
}

if(systemVar.web_admin.web){
    var buildJs = require("./app/MainApp/resources/js/webBuild.js");
    buildJs(fs,mix);
    mix.js("resources/assets/src/web-entry-point.js", "dist/webapp.js").version();//web
    mix.copyDirectory("resources/assets/vendor/webcss", publicPath + "/dist/vendor/webcss")//web
}

// Core Stylesheets

if(systemVar.web_admin.web || systemVar.web_admin.full_vue) {
    if(systemVar.web_admin.theme_custom==1){
        mix.sass(
            "app/MainApp/resources/themes/theme-" +
            systemVar.web_admin.theme +
            ".scss",
            "dist/css/theme-app.css"
        );//web & full vue
    }else{
        mix.sass(
            "resources/assets/src/vendor/styles/theme-" +
            systemVar.web_admin.theme +
            ".scss",
            "dist/css/theme-app.css"
        );//web & full vue

    }
    mix.sass(
        "resources/assets/src/vendor/styles/bootstrap.scss",
        "dist/css/bootstrap.css"
    )//web & full vue
    .sass(
        "resources/assets/src/vendor/styles/appwork.scss",
        "dist/css/appwork.css"
    )//web & full vue
    .sass(
        "resources/assets/src/vendor/styles/colors.scss",
        "dist/css/colors.css"
    )//web & full vue
    .sass(
        "resources/assets/src/vendor/styles/uikit.scss",
        "dist/css/uikit.css"
    )//web & full vue
    .copyDirectory("app/MainApp/resources/assets", publicPath + "/assets")//web & full vue
    .copyDirectory("resources/assets/images", publicPath + "/assets/images")//web & full vue
    .copyDirectory("resources/assets/src/inlinevue", publicPath + "/dist/inlinevue")//web & full vue
    .copyDirectory("resources/assets/vendor/libs", publicPath + "/dist/vendor/libs");//web & full vue
}

// copy semua assets di module2 di MainApp
(glob.sync("app/MainApp/Modules/*/resources/assets") || []).forEach(f => {
    f = f.replace(/[\\\/]+/g, "/");
    mix.copyDirectory(f, path.normalize(publicPath + "/assets"));
});

// copy semua assets di module2 di composer package
(glob.sync("vendor/hp-synapse/*/src/resources/assets") || []).forEach(f => {
    f = f.replace(/[\\\/]+/g, "/");
    mix.copyDirectory(f, path.normalize(publicPath + "/assets"));
});

if(systemVar.web_admin.full_vue){
    mix.sass("resources/assets/src/style.scss", "dist/css/style.css")//full vue
    mix.scripts("node_modules/bootstrap/dist/js/bootstrap.js", publicPath + "/dist/vendor/libs/bootstrap.js");//full vue
    mix.scripts("node_modules/popper.js/dist/popper.js", publicPath + "/dist/vendor/libs/popper/popper.js");//full vue
    mix.sass("resources/assets/src/vendor/styles/pages/authentication.scss", "dist/css/authentication.css");//full vue
}

if (Mix.isUsing("hmr")) {
    mix.disableNotifications();
} else {
    mix.version();
}
